### ISSUE TITLE
Remove POST method for /xxx/<id>?

### ISSUE THREAD

**Issue by CunliangGeng** [c-martinez/FAIRDataPoint#18]
Here, the `xxx` is catalog, dataset or distribution.

Currently, posting metadata to `$host/xxx/<id>` does not check if the subject in metadata is consistent with the post destination URL, .e.g. it works well now when the subject is  `$host/xxx/id001` while the destination URL is `$host/xxx/id555`,  which will confuse users.
 
The POST method is redundant for `/xxx/` and `/xxx/<id>`.  It should be fine to remove POST method for `/xxx/<id>`.

**Comment by CunliangGeng** [comment]
@c-martinez what do you think about this question? I prefer removing it to avoid troubles and confusions.

**Comment by c-martinez** [comment]
I agree it is redundant. The `id` is part of the POST body, right? So the we could remove POST methods `/xxx/<id>`.

**Comment by CunliangGeng** [comment]
yep, the `id` is part and the POST body. OK, will remove it.
